### ISSUE TITLE
signs eat backslashes

### ISSUE THREAD

**Issue by Niklp09** [mt-mods/display_modpack#2]
write a sign containing "\\", it's displayed properly, but when you edit it again, formspec treating them as escapes and they disappear

yl issue: https://gitea.your-land.de/your-land/bugtracker/issues/5016

**Comment by OgelGames** [comment]
Looks like it's missing a `minetest.formspec_escape()`, which is bad :eyes:

https://github.com/mt-mods/display_modpack/blob/e0e03058362e038d07d4063c4fbd6999ad27109c/signs_api/init.lua#L32 https://github.com/mt-mods/display_modpack/blob/e0e03058362e038d07d4063c4fbd6999ad27109c/signs_api/init.lua#L62-L63

Only problem is you can't just escape the text before saving it in `display_text`, because that string is also used for creating the entities, so you would see the escapes.
